---
- name: Create databases and users and then import Database movieDB and BookDB
  hosts: MyChameleonDB       # specified in the MyInventory file
  remote_user:  cc          # note that the user is cc for the
  strategy: debug
  become: yes               # run as sudo
  gather_facts: no          # do not gather facts from remote machine
  
  tasks:
    - name: Create a new bookdatabase
      mysql_db: name=bookstore state=present collation=utf8_unicode_ci
      
    - name: Create a new movieDB
      mysql_db: name=movieDB state=present collation=utf8_unicode_ci
      
    - name: create database user 'user_team3'
      mysql_user: name=user_team3 password=team3 priv='*.*:ALL' state=present host=192.168.2.172
      
    - name: Import Database Movie DB to movieDB
      mysql_db : movieDB state=import target=/home/cc/phpMySQLapp/mySqlDB/movieDB.sql
      
    - name: Import Database Book DB to bookstoreDB
      mysql_db : bookstore state=import target=/home/cc/phpMySQLapp/mySqlDB/bookDB.sql    
...
