---
 - name: Install Applications on Web server2
   shell: |
     cd  
     my_val=$(cat resultDBServerIP | awk -F':' '{print $11}' | awk -F'"' '{print $2}')
     sudo sed -i '$ a\[MyChameleonDB]' /etc/ansible/hosts
     sudo sed -i '$ a\'$my_val' ansible_connection=ssh ansible_ssh_private_key_file=~/.ssh/team3_key2.pem' /etc/ansible/hosts
     sudo sed -i '$ a\[MyLocalVms]' /etc/ansible/hosts
     sudo sed -i '$ a\127.0.0.1 ansible_connection=local' /etc/ansible/hosts
...