---
  ###########################################
  # Play : Now install packages on DB server on Chameleon
  ###########################################
  - name: "Master File installing basic packages on Chameleon VM"
    hosts: MyChameleonVMs       # specified in the MyInventory file
    remote_user:  cc          # note that the user is cc for the
                              # chameleon vm
    strategy: debug
    become: yes               # run as sudo
    gather_facts: no          # do not gather facts from remote machine

    ### All the tasks related to the Chameleon VM ###
    tasks:  

    # first install a bunch of packages on the chameleon VM
    - include: playbook_install_Applications.yml
...

