---
- name: Install Applications on DB server
  hosts: MyChameleonDB       # specified in the MyInventory file
  remote_user:  cc          # note that the user is cc for the
  strategy: debug
  become: yes               # run as sudo
  gather_facts: no          # do not gather facts from remote machine
  
  tasks:
    - name: Install Applications on DB server execution
      shell: |
        apt-get install -y git
        sudo apt-get -y install mysql-server
        sudo apt-get install python-mysqldb
        cd /home/cc
        git clone https://github.com/hoonheelee0202/team3_key.git
        cp /home/cc/team3_key/ipModify.sh /home/cc/
        cd /home/cc/
        git clone https://github.com/doc-vu/phpMySQLapp
        sudo sed -i -e 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mysql.conf.d/mysqld.cnf
...
