- name: Copy file From Local VM to ChameleonVMs
  hosts: MyChameleonVMs
  remote_user: cc
  tasks:
    #task1
    - name: Copy file execution1
      copy:
        src: /vagrant/ipModify.sh
        dest: /home/cc/
    - name: Copy file execution2
      copy:
        src: /vagrant/resultWebServerIP
        dest: /home/cc/resultWebServerIP
    - name: Copy file execution3
      copy:
        src: /vagrant/resultDBServerIP
        dest: /home/cc/resultDBServerIP
...
