---
- name: Install Applications on Web server2
  hosts: MyChameleonVMs       # specified in the MyInventory file
  remote_user:  cc          # note that the user is cc for the
  strategy: debug
  become: yes               # run as sudo
  gather_facts: no          # do not gather facts from remote machine
  
  tasks:
    - name : Install Shell execution 1.5 - ssh connect
      shell: |
        cd /home/cc/
        sudo /bin/sh ssh_connect_dbserver_ipmodify.sh
        sudo /bin/sh ssh_connect_dbserver.sh
...
