---
 - name: Install Applications on DB server
   shell: |
     sudo apt update
     sudo apt -y install apache2
     sudo /etc/init.d/apache2 restart
     sudo apt-get -y install php libapache2-mod-php php-mysql
     sudo systemctl restart apache2
     cd /var/www/html/
     git clone https://github.com/doc-vu/phpMySQLapp
     sudo sed -i -e 's/127.0.0.1/192.168.2.47/g' /var/www/html/phpMySQLapp/books/includes/bookDatabase.php
     sudo sed -i -e 's/127.0.0.1/192.168.2.47/g' /var/www/html/phpMySQLapp/movies/includes/movieDatabase.php
...

